# -*- coding: utf-8 -*-
"""Igea-Martins-desafio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10UKFhQ-hUGKyXNC126nGX8mX1zeGfo4r
"""

# Calculadora v2

num1 = int(input("digite o valor 1: "))

num2 = int(input("digite o valor 2: "))

resultado1 = num2 / num1

resultado2 = num1 * num2

if(num1 == 1 and num2 == num2):
  print(resultado1)

elif(num2 == 2 and num1 != 0):
  print(resultado2)

else:
    print("entradas inválidas")

print("fim do programa")

# Calculadora v1

num1 = int(input("digite o valor 1: "))

num2 = int(input("digite o valor 2: "))

resultado1 = num2 / num1

resultado2 = num1 * num2

if(num1 == 1 and num2 == num2):
  print(resultado1)

elif(num2 == 2 and num1 != 0):
  print(resultado2)

else:
    print("entradas inválidas")

print("fim do programa")