# -*- coding: utf-8 -*-
"""Igea-Martins-desafio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10UKFhQ-hUGKyXNC126nGX8mX1zeGfo4r
"""

# Calculadora v0
num1 = int(input("digite o valor 1: "))

num2 = int(input("digite o valor 2: "))

resultado = num1 + num2

if(num1 == num1 and num2 == num2):
  print(resultado)

print("fim do programa")